name: sample
on: 
  push:
  workflow_dispatch:
jobs:
  myfirstjob:
     runs-on: ubuntu-latest
     steps:
        - name: hi
          run: echo "hi from workflow action"
        - name: checkout code
          uses: actions/checkout@v5
          with:
            repository: https://github.com/BaluUdhaya/git_devops

