name: sample
on: 
  push:
  workflow_dispatch:
jobs:
  myfirstjob:
     runs-on: ubuntu-latest
     steps:
        - name: hi
          run: echo "hi from workflow action"
        - name: checkout code
          uses: actions/checkout@v5
          with:
            repository: BaluUdhaya/DevOpsCodeDemo
        - name: set up java
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: 'maven'
        - name: package code
          run: mvn package
            

