name: sample
on: 
  push:
  workflow_dispatch:
jobs:
  myfirstjob:
     runs-on: ubuntu-latest
     steps:
        - name: hi
          run: echo "hi from workflow action"
        - name: checkout code
          uses: actions/checkout@v5
          with:
            repository: BaluUdhaya/DevOpsCodeDemo
        - name: set up java
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: 'maven'
        - name: package code
          run: mvn package
        - name: test code
          run: |
            echo "code tested"
            mvn test
        - name: integrate with jenkins
          uses: appleboy/ssh-action@v1
          with:
              host: 13.204.154.55
              username: 'labuser'
              password: 'Nuvelabs123$'
              port: 22
              script: curl -l -u admin:Root123$ http://localhost:8080/job/project1/build?token=balu

            

