name: sample
on: 
  push:
  workflow_dispatch:
jobs:
  myfirstjob:
     runs-on: ubuntu-latest
     steps:
        - name: hi
          run: echo "hi from workflow action"
        - name: checkout code
          uses: actions/checkout@v5
          with:
            repository: BaluUdhaya/DevOpsCodeDemo
        - name: set up java
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: 'maven'
        - name: package code
          run: mvn package
        - name: test code
          run: |
            echo "code tested"
            mvn test
        - name: integrate with jenkins
          uses: cross-the-world/ssh-scp-ssh-pipelines@latest
          with:
              host: 13.204.154.55
              user: 'labuser'
              pass: 'Nuvelabs123$'
              port: 22
              connect_timeout: 10s
            

